title: JAUNTS
#author:
#  name: Avijit Thawani
#  email: thawani@usc.edu

theme: minima

header_pages:
  - index.md
  - members.md
  - publications.md
  - join.md

minima:
  social_links:
    twitter: placeholder
    github:  placeholder
    instagram: placeholder
    linkedin: placeholder
    facebook: placeholder
    pinterest: placeholder
    youtube: placeholder
